### PR TITLE
Coercible types can be used to validate

### PR DESCRIPTION
**Pull request by faucct**
Hello. I was searching for a way to have a coercing sanitizing schema. Added specs have the configuration I expected to work.

### CODE REVIEW

**Comment by faucct** [comment]
Can someone take a look?

**Comment by thefliik** [comment]
See #406, I don't believe they are currently accepting PR for this library.

**Comment by solnic** [comment]
This API was removed in favor of type specs that are now always used in dry-schema, this gem will be used as the schema backend in dry-validation 1.0.0.

**Comment by solnic** [comment]
> See #406, I don't believe they are accepting PR for this library.

We do accept PRs, unfortunately it was decided to rewrite it on top of dry-schema (https://discourse.dry-rb.org/t/plans-for-dry-validation-dry-schema-a-new-gem/215) and due to lack of time maintaining 0.x was not possible.

**Pull request closed without merging**
