### PR TITLE
Simplify error compiler

### LINKED ISSUE #200: input(:hash?) flattens other error responses and sometimes adds nil keys
After seeing #194 closed, I started playing around with `0.8.0`. I tried two different schemas with and without `input(:hash?)` and got incorrect results when using `input(:hash?)`

See my test script below:

```ruby
require 'dry/validation'

# First Schema (without input(:hash?))

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:bar).filled
      required(:baz).filled
    end
  end

begin
  schema.call(nil).messages
rescue => error
  puts error # => undefined method `key?' for nil:NilClass
end
# OK -- or at least expected

puts schema.call({}).messages # => {:foo=>["is missing"]}
# OK

puts schema.call(foo: nil ).messages # => {:foo=>["must be a hash"]}
# OK

puts schema.call(foo: {}).messages # => {:foo=>{:bar=>["is missing"], :baz=>["is missing"]}}
# OK

puts schema.call(foo: { bar: nil, baz: nil}).messages # => {:foo=>{:bar=>["must be filled"], :baz=>["must be filled"]}}
# OK

puts schema.call(foo: { bar: 'hi', baz: 'bye'}).messages # => {}
# OK

puts '-' * 80

# First Schema again (with input(:hash?))

schema =
  Dry::Validation.Schema do
    input(:hash?)

    required(:foo, :hash).schema do
      required(:bar).filled
      required(:baz).filled
    end
  end

puts schema.call(nil).messages # => must be a hash
# OK, cool

puts schema.call({}).messages # => {:foo=>["is missing"]}
# OK

puts schema.call(foo: nil ).messages # => {:foo=>["must be a hash"]}
# OK

puts schema.call(foo: {}).messages # => {:bar=>["is missing"], :baz=>["is missing"]}
# NOT OK - what happened to foo: ?

puts schema.call(foo: { bar: nil, baz: nil}).messages # => {:bar=>["must be filled"], :baz=>["must be filled"]}
# NOT OK - what happened to foo: ?

puts schema.call(foo: { bar: 'hi', baz: 'bye'}).messages # => {}
# OK

puts '*' * 80

# Second Schema (without input(:hash?))

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:bar, :hash).schema do
        required(:baz).filled
      end
    end
  end

puts schema.call(foo: { bar: {} }).messages #=> {:foo=>{:bar=>{:baz=>["is missing"]}}}
# OK

puts '-' * 80

# Second Schema again (with input(:hash?))

schema =
  Dry::Validation.Schema do
    input(:hash?)

    required(:foo, :hash).schema do
      required(:bar, :hash).schema do
        required(:baz).filled
      end
    end
  end

puts schema.call(foo: { bar: {} }).messages # => {:foo=>{:bar=>{nil=>{:baz=>["is missing"]}}}}
# NOT OK - what is nil doing in there?
```

The important cases are:

`{:foo=>{:bar=>["is missing"], :baz=>["is missing"]}}` v.s. `{:bar=>["is missing"], :baz=>["is missing"]}`

`{:foo=>{:bar=>["must be filled"], :baz=>["must be filled"]}}` v.s. `{:bar=>["must be filled"], :baz=>["must be filled"]}`

and

`{:foo=>{:bar=>{:baz=>["is missing"]}}}` v.s. `{:foo=>{:bar=>{nil=>{:baz=>["is missing"]}}}}`

### LINKED ISSUE #201: Duplicated keys in nested schemas produce incorrectly nested validation messages
It appears that keys that have a parent key with the same name clobber the nesting structure of output messages.

See my test script:

```ruby
require 'dry/validation'

# With duplicate keys

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:foo).filled
    end
  end

puts schema.call({}).messages # => {:foo=>["is missing"]}
# OK

puts schema.call(foo: {}).messages # => {:foo=>["is missing"]}
# NOT OK - I expected {:foo=>{:foo=>["is missing"]}}

puts schema.call(foo: { foo: 'iamfilled' }).messages
# OK

puts '*' * 80

# Renaming the inner foo to bar

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:bar).filled
    end
  end

puts schema.call({}).messages # => {:foo=>["is missing"]}
# OK

puts schema.call(foo: {}).messages # => {:foo=>{:bar=>["is missing"]}}
# OK

puts schema.call(foo: { bar: 'iamfilled' }).messages # => {}
# OK

puts '*' * 80

# Also occurs with other keys between the duplicates in the hierarchy

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:bar, :hash).schema do
        required(:foo).filled
      end
    end
  end

puts schema.call({}).messages # => {:foo=>["is missing"]}
# OK

puts schema.call(foo: {}).messages # => {:foo=>{:bar=>["is missing"]}}
# OK

puts schema.call(foo: { bar: {} }).messages # => {:bar=>{:foo=>["is missing"]}}
# NOT OK - what happened to the first :foo?

puts schema.call(foo: { bar: { foo: 'iamfilled' } }).messages # => {}
# OK
```

### PR DESCRIPTION
**Pull request by solnic**
This is a refactor that fixes a ton of bugs by:

* Removing `ErrorCompiler::Input`
* Extracting common `MessageCompiler`
* Changing `ErrorCompiler` to inherit from `MessageCompiler`
* Changing `HintCompiler` to inherit from `MessageCompiler`
* Adding `MessageSet` which compilers now return, which encapsulates producing error hashes and merging hints in
* Expanding `Message` API and adding `Hint` message type too
* Opening doors for future refactor for 0.9.0 version as we can get rid of `[:input, ...]` nodes in the result ast in dry-logic so compilation should become simpler/faster

Results:

* Down to 8 pending specs from 34
* Fixes hints for `each` where hints wouldn't be added for errors of individual elements
* Fixes hints for `each` where element hints are added for the array itself
* Fixes #200 
* Fixes #201

There are more things that could be improved and simplified but I want to release this under 0.8.1 and it's already a big diff ;)

Public API stays the same, notice that changes in the specs were needed only in places where bugs were fixed (including one spec that had an incorrect expectation...) so I removed `xit`. Changes in compiler specs were needed because we now return `MessageSet` instead of a plain `Hash` but it's not a public API (yet).

### CODE REVIEW

**Comment by solnic** [comment]
@fran-worley @timriley @AMHOL could you take a look at this? Digesting the diff is gonna be hard although it's mostly moving things around and removing redundant stuff

**Comment by fran-worley** [comment]
@solnic looking good!!

**Comment by backus** [comment]
Might be helpful also to have @dgollahon verifying this fixes #200 and #201.

**Comment by solnic** [comment]
@backus @dgollahon that would be helpful, although I haven't changed the way `input :hash?` works, but I did fix the issues with nested errors and nils sneaking in (still a workaround rather than the actual fix, but should work for now)

**Comment by dNitza** [comment]
Hi!

I've been testing this branch out because of a missing error key (I suspect related to #200 ) and have come across the following issue.

Given a schema like:
```ruby
  Dry::Validation::Schema::Form do
    configure do
      config.messages = :i18n
    end
    
    required(:content).schema do
      required(:borrowers).each do
        schema do
          required(:member_name).schema do
            required(:first_name).filled  
          end
        end
      end
    end
  end
```

And the following input:

```ruby
{ 
  "content"=>{
    "borrowers"=>[
      {"member_name"=>{"first_name"=>""}},
      {"member_name"=>{"first_name"=>""}}
    ]
  }
}
```

I get the following error: `undefined method 'signature' for "must be filled":String` in `/dry/validation/message_set.rb: in uniq!, line 50`.

Prior to updating our app to this branch, our validation message hash was missing the `member_name` key:

```ruby
{
  :content=>{
    :borrowers=>{
        0=>{:first_name=>["must be filled"]}, 
        1=>{:first_name=>["must be filled"]}
    }
  }
}
```

**Comment by dgollahon** [comment]
@solnic 

Checked on the project all tests passed and it solved my issue, huzzah!

When I re-ran my script from #201 I stumbled across an error. Here's the test script and output annotated as before:

```ruby
require 'dry/validation'

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:foo, :hash).filled
    end
  end

puts schema.call({}).messages # => {:foo=>["is missing"]}
# OK

puts schema.call(foo: {}).messages rescue p $! # => #<TypeError: no implicit conversion of Symbol into Integer>
# NOT OK
# NOTE: schema.call(foo: {}) does not raise an error

puts schema.call(foo: { foo: 'bar' }).messages # => {}
# OK

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:foo, :hash).schema do
        required(:bar, :hash).filled
      end
    end
  end

puts '*' * 80

puts schema.call({}).messages # => {:foo=>["is missing"]}
# OK

puts schema.call(foo: {}).messages rescue p $! # => #<TypeError: no implicit conversion of Symbol into Integer>
# NOT OK
# NOTE: schema.call(foo: {}) does not raise an error

puts schema.call(foo: { foo: {} }).messages # => {:foo=>{:foo=>{:bar=>["is missing"]}}}
# OK

puts schema.call(foo: { foo: { bar: 'baz' } }).messages # => {}
# OK
```

**Comment by dgollahon** [comment]
Running the script from #200 though surfaced no issues and outputs what I would expect. When I reintroduced the `input :hash?` into our app locally, however, it caused the issue to reappear where a second `data` key is dropped. I'll update this comment when I can find a minimal test case that can reproduce the issue.

**Comment by dgollahon** [comment]
Another weird case:

```ruby
require 'dry/validation'

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:bar, :hash).filled
    end
  end

puts schema.call(foo: {}).messages # => {:foo=>{:bar=>["is missing"]}}
# OK

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:foo, :hash).filled
    end
  end

schema.call(foo: {}).messages rescue p $! # => #<TypeError: no implicit conversion of Symbol into Integer>
# NOT OK - What?
```

Those two cases should be identical minus the duplicate `:foo` in the second one.

**Comment by dgollahon** [comment]
I also confirmed the args issue from https://github.com/dry-rb/dry-validation/issues/200#issuecomment-230062688 still applies.

[sorry if all these at once is overwhelming!]

**Comment by dgollahon** [comment]
Another peculiar case:

```ruby
require 'dry/validation'

schema =
  Dry::Validation.Schema do
    input :hash?

    required('data', :hash).schema do
      required('data', :hash).schema do
        required('id')#.filled(:str?)
      end
    end
  end

puts schema.call(
  'data' => {
    'data' => {
      'type' => 'foo'
    }
  }
).messages

# ... rule_compiler.rb:18:in `visit': undefined method `visit_' for #<Dry::Validation::SchemaCompiler:0x007fbeb338f210> (NoMethodError)
```

Seems like maybe a nil is sneaking through and getting interpolated?

**Comment by solnic** [comment]
@dgollahon if you want to use `required('id')` w/o any value predicates *and* you don't use `type_specs` then it's expected to crash, and I won't be fixing it since inferring coercions (which is what crashes) is going away in 1.0

The rest of the issues look like bugs that I still need to fix, so...I'm on it. Thanks for checking this.

**Comment by solnic** [comment]
@dNitza hey Daniel, I fixed that as well

**Comment by solnic** [comment]
@dgollahon I think I fixed the issue with duped key names in subsequent nested schemas...pls check it out; as far as `input :hash?` goes, I'll improve this separately from this PR (it's outside of the scope of what I'm doing here)

**Comment by dNitza** [comment]
Amazing! Can verify that works! Thanks @solnic 💯  :)

**Comment by solnic** [comment]
@dgollahon @dNitza this is now in master, thanks for testing :) I'll do the final fix/improvement for `input :hash?` feature and push 0.8.1 on Friday.

**Comment by dgollahon** [comment]
@solnic thanks for all the hard work on this

re: missing predicates and type specs, as long as that's going away in 1.0 sounds great.

As far as `input` being out of scope, I figured some of what I posted would be--looking forward to the fixes whenever you have a chance.

Unfortunately, I found one more issue when I tried out master. Looks like one more case of the duplicate key nesting bug is back:

```ruby
require 'dry/validation'

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:foo, :hash).schema do
        required(:bar, :hash).filled
      end
    end
  end

puts schema.call(foo: {}).messages # => {:foo=>{:foo=>["is missing"]}}
# OK

puts schema.call(foo: { foo: {} }).messages # => {:foo=>{:bar=>["is missing"]}}
# NOT OK -- we lost a :foo
```

I know at some point last night that case was not an issue, but it seems to have crept in since I last tested.

**Comment by solnic** [comment]
@dgollahon should be fixed via https://github.com/dry-rb/dry-validation/commit/3eacdfae7e78cfe522517c13b37699fa9808e883

**Comment by dgollahon** [comment]
thanks @solnic! looks like that works with all the non-`input :hash?` cases i have handy. :)

**Pull request merged**
