### PR TITLE
Parse list tokens as comma separated list in msgs

### LINKED ISSUE #609: rules list parsing error
```ruby
class MyContract < Dry::Validation::Contract
  params do
    required(:hogwarts_house).hash do
      required(:head).filled(:string)
      required(:common_room).hash do
        required(:name).filled(:string)
        required(:location).filled(:string)
      end
    end
  end

  rule('hogwarts_house.common_room.location') do
    unless %w[tower underground].include?(value)
      key.failure(:invalid, list: %w[tower underground])
    end
  end
end
```

produces:
`Hogwarts house common room location must be one of: [\"tower\", \"underground\"]`

```ruby
class MyContract < Dry::Validation::Contract
  params do
    required(:hogwarts_house).hash do
      required(:head).filled(:string)
      required(:common_room).hash do
        required(:name).filled(:string)
        required(:location).filled(:string, included_in?: %w[tower underground])
      end
    end
  end
end
```
produces:
`Hogwarts house common room location must be one of: tower, underground`

### PR DESCRIPTION
**Pull request by waiting-for-dev**
Fixes #609

### CODE REVIEW

**Comment by solnic** [comment]
@waiting-for-dev thanks! could you update the CHANGELOG.md in master?

**Comment by waiting-for-dev** [comment]
hey @solnic , changelog updated!

**Comment by solnic** [comment]
@waiting-for-dev sweet, thank you :) btw I have an idea to automate that - we could establish a PR template with a special section for a changelog entry and then, after the PR is merged, a GH action could extract the entry and update the CHANGELOG file.

**Comment by waiting-for-dev** [comment]
That would be super cool :)

**Pull request merged**
