### PR TITLE
workaround for #618

### PR DESCRIPTION
**Pull request by sirfilip**
Bit ugly workaround but could not find better place to apply the full: true rule. 

Not really happy with it and looknig forward to change it if needed.

### CODE REVIEW

**Comment by sirfilip** [comment]
Thanks @solnic wow this helps a lot :) will apply the changes tonight.

**Comment by sirfilip** [comment]
I see specs are failing on a random bases. Will investigate.

**Comment by sirfilip** [comment]
I have done some bisecting and
```
rspec './spec/integration/contract/class_interface/rule/nested_data_spec.rb[1:1:1:1]' './spec/integration/contract/evaluator/using_context_spec.rb[1:1:1]' --seed 12674

rspec './spec/extensions/hints/result_spec.rb[1:1:1:1]' './spec/integration/contract/class_interface/rule/nested_data_spec.rb[1:1:1:1]' --seed 60482
```
Are causing the failure probably conflicting with 

```ruby
# spec/integration/contract/evaluator/using_context_spec.rb
before(:all) do
  Dry::Validation.load_extensions(:hints)
end

# spec/extensions/hints/result_spec.rb
before { Dry::Validation.load_extensions(:hints) }
```
Will see what could be the problem and solve it.

**Comment by solnic** [comment]
@sirfilip I already merged it in - thank you! spec suite stability can be addressed via a separate PR

**Pull request merged**
