### PR TITLE
Update for latest dry-configurable setting API

### PR DESCRIPTION
**Pull request by timriley**

### CODE REVIEW

**Review by solnic — COMMENTED** [review]
I think I want to make it work with both versions until 2.0.0. Thoughts?

**Comment by timriley** [comment]
@solnic good thought, and I think you're right, particularly for the post-1.0 gems of ours. Do you have any thoughts about how to go about it?

**Comment by timriley** [comment]
@solnic I like what you did over in [`0471911` (dry-schema #356)](https://github.com/dry-rb/dry-schema/pull/356/commits/0471911aa95a184f594cfded07f762becad09489) — would you be happy with that approach here too?

**Comment by solnic** [comment]
@timriley yes sorry that's what I meant 🙂 the only "issue" is that we would have to ensure the new dry-validation depends on the new dry-schema too...unless you want to override `setting` here as well?

**Comment by timriley** [comment]
@solnic Yeah, I think we'd want to put this shim directly in every gem that uses such an approach

**Comment by solnic** [comment]
@timriley done here c8ad125

**Comment by timriley** [comment]
Thanks to the improved backwards compatibility in the upcoming dry-configurable deprecations, this one no longer needed any kind of additional shim.

**Pull request merged**
