### PR TITLE
Allow multiple validations on one field

### PR DESCRIPTION
**Pull request by kimquy**
Fix this issue https://github.com/dry-rb/dry-validation/issues/299

Thanks @nicolas-besnard for the lovely spec. Hope that's fine when I use it in this PR.

### CODE REVIEW

**Comment by solnic** [comment]
Thank you :)

**Comment by nicolas-besnard** [comment]
@solnic any news about the releases of 0.10.7 with this fix ?

**Comment by solnic** [comment]
@nicolas-besnard I'll release it tomorrow

**Comment by solnic** [comment]
@nicolas-besnard well, 8 days later, I finally released it ;)

**Pull request merged**
