### PR TITLE
Fix rule.each on optional value

### PR DESCRIPTION
**Pull request by bautrey37**

### CODE REVIEW

**Comment by bautrey37** [comment]
I am now getting this rubocop warning after the change. 
```
lib/dry/validation/rule.rb:79:7: C: Metrics/AbcSize: Assignment Branch Condition size for each is too high. [<8, 24, 6> 26/25]
```

I'm not sure what I can do to fix it.

**Comment by solnic** [comment]
Thanks for opening this PR. There was an issue with our CI setup in main, I just fixed it so could you rebase this branch and f-push? Also, don't worry about that rubocop warning.

**Comment by esparta** [comment]
Sometimes Rubocop is very picky and can be configure to have that ABC rule less _problematic_
Maybe is also time to reduce the amount of deepness in the method, from `proc` -> `unless` -> `each_with_index` to `proc` -> `each_with_index`

```diff
index bc05267..45ba724 100644
--- a/lib/dry/validation/rule.rb
+++ b/lib/dry/validation/rule.rb
@@ -82,16 +82,16 @@ module Dry
         @keys = []

         @block = proc do
-          unless result.base_error?(root) || !values.key?(root)
-            values[root].each_with_index do |_, idx|
-              path = [*Schema::Path[root].to_a, idx]
+          next if skip_values_evaluation?(root)

-              next if result.schema_error?(path)
+          values[root].each_with_index do |_, idx|
+            path = [*Schema::Path[root].to_a, idx]

-              evaluator = with(macros: macros, keys: [path], index: idx, &block)
+            next if result.schema_error?(path)

-              failures.concat(evaluator.failures)
-            end
+            evaluator = with(macros: macros, keys: [path], index: idx, &block)
+
+            failures.concat(evaluator.failures)
           end
         end

@@ -100,6 +100,15 @@ module Dry
         self
       end

+      # Helper to determine the need for value's review
+      #
+      # @api private
+      def skip_values_evaluation?(root)
+        result.base_error?(root) || !values.key?(root) || !values.key?(root)
+      end
```

**Comment by solnic** [comment]
@esparta thanks, we can address the metric separately from this PR though 😄

**Pull request merged**
