### PR TITLE
Revert "Sync with schema changes in dry-types"

### PR DESCRIPTION
**Pull request by flash-gordon**
Reverts dry-rb/dry-validation#443

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Any reason for this? `dry-types` 0.14 doesn't work in my app due to https://github.com/dry-rb/dry-types/pull/287 and that is only fixed in 0.15.

**Comment by flash-gordon** [comment]
Yes, there are quite specific reasons, dry-types doesn't provide the API required for dry-validation < 1.0 anymore so it's not possible to use these two gems together. I cut a branch for dry-types 0.14 and cherry-picked the fix you referenced. I'll push 0.14.1 shortly.

**Comment by flash-gordon** [comment]
https://rubygems.org/gems/dry-types/versions/0.14.1

**Comment by rafaelfranca** [comment]
Thank you so much ❤️

**Pull request merged**
