### PR TITLE
Update config in configure blocks only

### PR DESCRIPTION
**Pull request by timriley**
Update all usages of dry-configurable-provided `config` so that any changes are made inside `configure` blocks.

This prepares for the changes in https://github.com/dry-rb/dry-configurable/pull/140.

### CODE REVIEW

**Comment by solnic** [comment]
I'm sorry but can this only include configure change? I don't want zeitwerk stuff to be in the main branch just yet. It's not ready (dry-core is not released) and it already caused two invalid releases of dry-schema (which is why I reverted zeitwerk changes in its main branch).

**Comment by timriley** [comment]
@solnic Yep, I can do this. Weirdly, dry-configurable in the `main` branch has already been updated to expect the Zeitwerk-enabled dry-core, which is why all these gems I'm testing with dry-configurable also need dry-core updated.

Do we want to keep zeitwerk-enabled dry-core? What is our plan for Zeitwerk in our other gems pre-1.0? Because I want to bring everything to 1.0 (at least as release candidates) basically in the next month.

**Comment by timriley** [comment]
What I'll do for starters is just revert the commit in dry-configurable's main branch that expects the zeitwerk-enabled dry-core.

**Comment by timriley** [comment]
@solnic FYI, with https://github.com/dry-rb/dry-configurable/pull/142 now merged, I've updated this branch so it is no longer changing anything related to requiring code.

**Pull request closed without merging**
