### PR TITLE
Integration tests for predicates

### LINKED ISSUE #146: Extensive integration test suite
While working on integration between `dry-v` and `hanami-v`, I wrote a test suite for all the builtin predicates.

It tests for missing, nil, blank strings, string values (eg. `"1"`), expected Ruby types (eg `1`), unexpected types (eg. a hash when an int is expected).

All these values are used to test all the six combinations of `required`/`optional` (for keys) and `value`, `filled`, `maybe` macros (for values).

All these combinations are tested both for `Schema` and `Form`.

This results in almost 3000 assertions which run in 3 seconds.

---

This extensive testing helped to spot issues in `dry-v` (and related gems) that I reported here.

Each time you folks apply a fix for these issues, I run `bundle update` and get the fixes (thank you!), but also new failures.

These new failures deserve new tickets. But that will make the feedback process really slow. It will take days to spot the new errors and a week to fix. If `dry-v` codebase will include these tests, feedback will become immediate and hopefully no broken code will be pushed.

**I believe that the `hanami-v` tests really belong here.**

I can take care of open a PR to add them here. But because it's a huge work, before to dive into it, I want to be sure that it will be accepted by you.

WDYT? @solnic @timriley @AMHOL Thank you!

### PR DESCRIPTION
**Pull request by jodosha**
Integration tests for schema and form predicates.

Closes #146

### CODE REVIEW

**Comment by jodosha** [comment]
@solnic @timriley @AMHOL Before to proceed with the rest of the test suite, please review this commit. Once will get this sorted with your feedback, I'll port the rest of the tests. Thanks!

**Comment by AMHOL** [comment]
:+1: Looks good to me, nice one @jodosha

**Comment by timriley** [comment]
👍 Looks good to me too!

**Comment by solnic** [comment]
👍

**Comment by jodosha** [comment]
Technical notes:

  * I had to use both `dry-logic` and `dry-types` from master as suggested by @solnic [here](https://gist.github.com/solnic/22527ceb407fc1e210e87a01256b7894).

  * There are 38 pending examples for `Form`. Almost all of them was reported as GH issue here. I had to put on pending to have a green build. I manually checked all these failures and the problem is still present as of: `dry-validation` at https://github.com/dry-rb/dry-validation/commit/8934d28a5240848fea0b349a28ea4d217376defa, `dry-types` at https://github.com/dry-rb/dry-types/commit/aa6fce1758db0255222dcb9e4c74a90c9968ac3e, and `dry-logic` at https://github.com/dry-rb/dry-logic/commit/e649fad58546e8e53a048d310c554ad910466a93

---

The test suite has now the following stats:

```shell
Finished in 4.56 seconds (files took 0.70018 seconds to load)
1671 examples, 0 failures, 38 pending
```

---

/cc @solnic @timriley @AMHOL Please review and hopefully merge it! 😉

**Comment by fran-worley** [comment]
I'm not sure if this is causing any of your issues but the new predicates (included_in, includes, excluded_from and excludes) in dry-logic master and your specs are not on master for dry-types or dry-validation yet.

I've not merged the change to master yet because I'm waiting for a new version of dry-logic to be released.

**Comment by solnic** [comment]
Thanks. This is amazing work. I'm pretty sure most of the pending specs will pass once we deal with dry-rb/dry-types#87

**Comment by solnic** [comment]
> I've not merged the change to master yet because I'm waiting for a new version of dry-logic to be released

Please merge support for these new predicates to master and let's just rely on master branches for specs for now

**Comment by fran-worley** [comment]
Ok, so there is no problem with relying on dry-logic from master for now?

**Comment by solnic** [comment]
@fran-worley nope, there were no breaking changes in dry-logic :)

**Comment by AMHOL** [comment]
Thanks for all your work on this @jodosha :heart:

**Comment by jodosha** [comment]
@fran-worley 
> I'm not sure if this is causing any of your issues but the new predicates (included_in, includes, excluded_from and excludes) in dry-logic master and your specs are not on master for dry-types or dry-validation yet.

Yes, this PR points to dry-logic master and already uses these new predicates 😄 .

**Comment by fran-worley** [comment]
I hadn't seen that a lot of my dry-v branch had already been incorporated into master. I'm adding another couple of spec files for predicates and have found some more examples of the failures you experienced.

I'll set them as pending and raise a PR.

Thanks for your great work the suite is really really good!



Sent from my iPhone

On 11 May 2016, at 08:22, Luca Guidi <notifications@github.com<mailto:notifications@github.com>> wrote:


@fran-worley<https://github.com/fran-worley>

I'm not sure if this is causing any of your issues but the new predicates (included_in, includes, excluded_from and excludes) in dry-logic master and your specs are not on master for dry-types or dry-validation yet.

Yes, this PR points to dry-logic master and already uses these new predicates ? .

-

**Pull request merged**
